parameters:
#    locationprueba.example.class: locationprueba\locationpruebaBundle\Example

services:
#    locationprueba.example:
#        class: %locationprueba.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
